### ISSUE TITLE
Generate first simulation data from GRF

### ISSUE THREAD

**Issue by skimslozo** [skimslozo/3dv#1]
First set of data shoud be generated using Google Football Research. Data shoud include:

1. Ground-truth 3D trajectory points of the ball:

- x, y, z [m] - position of the ball in the world frame at a T [timestamp]

2. 2D projected trajectories of the ball from 2 calibrated cameras (perhaps trajectories themselves not necessary, if we have the camera info then we should be able to project the 3D trajectory). Requirements:

- u, v position of the ball [pix]  at a specific timestamp T from at least 2 camera views
- Ideally, T (approximately) the same for both cameras
- In case it is not explicitly possible, we estimate the 2D trajectories ourselves by projecting the 3D path on multiple 2D image panes. Can be done either by implementing in GRF side, or on our side. 

3. Camera calibration info. This includes:

- Camera pose matrix [R|T] in the world coordinates
- Camera internal calibration matrik K

For now, the data type is not relevant/tbd as the task advances. Let's keep each other updated on progress within this issue

**Comment by jjannik** [comment]
@skimslozo  I think I found out where to change the camera settings and so on (see my last commit). but its basically inside match.cpp. Let's see what the picture that we get from fifa look like

**Comment by skimslozo** [comment]
https://github.com/skimslozo/3dv/pull/11
