### ISSUE TITLE
Smooth trajectory/interpolation

### ISSUE THREAD

**Issue by kannwism** [skimslozo/3dv#14]
Generate a smooth trajectory of the ball. Reject outliers. Maybe by fitting some sort of curve.

**Comment by skimslozo** [comment]
We should be able to also detect bounces, or, more generally, changes in direction due to collisions with a foot, player, or the ground, so I would say just interpolation would not correspond to the true trajectory.

**Comment by skimslozo** [comment]
> We should be able to also detect bounces, or, more generally, changes in direction due to collisions with a foot, player, or the ground, so I would say just interpolation would not correspond to the true trajectory.

As an idea in response to the above - perhaps for each 3D correspondence point, we check how similar the current trajectory up to that point is to a trajectory describing a 3D projectile motion without any collisions at that time stamp, and then set some treshold? If it's close enough, we fit a trajectory/curve. If not, then we just start a new trajectory from that specific point, and connect it to the end point of the previous one with a straight line or something.

**Comment by kannwism** [comment]
Some very basic trajectory interpolation was implemented in 521d1f2905259f0e5e2e84e8bf9842aeb2a25b7f.

The visualization of the the line is still a bit thin and I don't know how to change it.
