### ISSUE TITLE
Implement a option to add noise in the data set generator

### ISSUE THREAD

**Issue by corkillj** [skimslozo/3dv#24]
Maybe various types of noise, maybe only certain cameras, maybe an offset for one camera or whatever.
Also maybe inject random complete non-sense outliers

**Comment by skimslozo** [comment]
How about noise generation for camera calibration, i.e. uncertainty in camera pose? Would be a reasonble point to investigate as well imo

**Comment by corkillj** [comment]
Basic gaussian noise was implemented by mari

**Comment by kannwism** [comment]
Gaussian noise implemented for 2d points, extrinsic and intrinsic matrices in 905c652a25f46f55c16eadb693ad39364135221c.

One can play around with the effect of noise in noise_analysis.py (ab7a0da8f74074c5334da1f97acee856c81962c7).
