### ISSUE TITLE
Generate trajecory video for real data

### ISSUE THREAD

**Issue by skimslozo** [skimslozo/3dv#31]
We would like to have a video with the football video stream on one side, and the trajectory the ball is taking in our visualizer on the other side.

**Comment by skimslozo** [comment]
Dependency on https://github.com/skimslozo/3dv/issues/29

**Comment by corkillj** [comment]
Dont know about "taking screenshots" in the visualizer, but i can give it a try, this would really only be for show though. Having all of the points in one visualizon should be easy

**Comment by corkillj** [comment]
done by Jannik
